<?php

namespace App\Models\Traits;

trait Uuid
{
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($model) {
            $model->setKeyType('string');
            $model->setIncrementing(false);
            $model->setAttribute($model->getKeyName(), \Str::uuid());
        });
    }
}
